-- MySQL Script generated by MySQL Workbench
-- 03/03/17 01:20:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artista` (
  `idArtista` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estampa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estampa` (
  `idEstampa` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `imagenes` VARCHAR(45) NULL,
  `tema` VARCHAR(45) NULL,
  `rating` VARCHAR(45) NULL,
  `popularidad` VARCHAR(45) NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`idEstampa`),
  INDEX `fk_Estampa_Artista1_idx` (`Artista_idArtista` ASC),
  CONSTRAINT `fk_Estampa_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `mydb`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `formaPago` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Camiseta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Camiseta` (
  `idEstampa` INT NOT NULL,
  `talla` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `material` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstampa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Camiseta_idEstampa` INT NOT NULL,
  `Artista_idArtista` INT NOT NULL,
  `Estampa_idEstampa` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Cliente_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Venta_Camiseta1_idx` (`Camiseta_idEstampa` ASC),
  INDEX `fk_Venta_Artista1_idx` (`Artista_idArtista` ASC),
  INDEX `fk_Venta_Estampa1_idx` (`Estampa_idEstampa` ASC),
  CONSTRAINT `fk_Venta_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Camiseta1`
    FOREIGN KEY (`Camiseta_idEstampa`)
    REFERENCES `mydb`.`Camiseta` (`idEstampa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `mydb`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Estampa1`
    FOREIGN KEY (`Estampa_idEstampa`)
    REFERENCES `mydb`.`Estampa` (`idEstampa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
