package arqSw.proyecto.Hibernate;
// Generated 3/03/2017 01:29:57 AM by Hibernate Tools 3.6.0



/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private int idAdministrador;
     private String usuario;
     private String password;

    public Administrador() {
    }

	
    public Administrador(int idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public Administrador(int idAdministrador, String usuario, String password) {
       this.idAdministrador = idAdministrador;
       this.usuario = usuario;
       this.password = password;
    }
   
    public int getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(int idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


