package arqSw.proyecto.Hibernate;
// Generated 3/03/2017 01:29:57 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estampa generated by hbm2java
 */
public class Estampa  implements java.io.Serializable {


     private int idEstampa;
     private Artista artista;
     private String nombre;
     private String descripcion;
     private String imagenes;
     private String tema;
     private String rating;
     private String popularidad;
     private String autor;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Estampa() {
    }

	
    public Estampa(int idEstampa, Artista artista) {
        this.idEstampa = idEstampa;
        this.artista = artista;
    }
    public Estampa(int idEstampa, Artista artista, String nombre, String descripcion, String imagenes, String tema, String rating, String popularidad, String autor, Set<Venta> ventas) {
       this.idEstampa = idEstampa;
       this.artista = artista;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.imagenes = imagenes;
       this.tema = tema;
       this.rating = rating;
       this.popularidad = popularidad;
       this.autor = autor;
       this.ventas = ventas;
    }
   
    public int getIdEstampa() {
        return this.idEstampa;
    }
    
    public void setIdEstampa(int idEstampa) {
        this.idEstampa = idEstampa;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getImagenes() {
        return this.imagenes;
    }
    
    public void setImagenes(String imagenes) {
        this.imagenes = imagenes;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }
    public String getPopularidad() {
        return this.popularidad;
    }
    
    public void setPopularidad(String popularidad) {
        this.popularidad = popularidad;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


