package arqSw.proyecto.Hibernate;
// Generated 3/03/2017 01:29:57 AM by Hibernate Tools 3.6.0



/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idVenta;
     private Cliente cliente;
     private Camiseta camiseta;
     private Estampa estampa;
     private Artista artista;
     private String fecha;

    public Venta() {
    }

	
    public Venta(int idVenta, Cliente cliente, Camiseta camiseta, Estampa estampa, Artista artista) {
        this.idVenta = idVenta;
        this.cliente = cliente;
        this.camiseta = camiseta;
        this.estampa = estampa;
        this.artista = artista;
    }
    public Venta(int idVenta, Cliente cliente, Camiseta camiseta, Estampa estampa, Artista artista, String fecha) {
       this.idVenta = idVenta;
       this.cliente = cliente;
       this.camiseta = camiseta;
       this.estampa = estampa;
       this.artista = artista;
       this.fecha = fecha;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Camiseta getCamiseta() {
        return this.camiseta;
    }
    
    public void setCamiseta(Camiseta camiseta) {
        this.camiseta = camiseta;
    }
    public Estampa getEstampa() {
        return this.estampa;
    }
    
    public void setEstampa(Estampa estampa) {
        this.estampa = estampa;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


